name: Trigger auto deployment for containerapp testappup-2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/testappup-2-AutoDeployTrigger-fcc7459e-c3b9-4f6f-a4fd-92b24ba579c2.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: catestappup25826093093acr.azurecr.io
          username: ${{ secrets.TESTAPPUP2_REGISTRY_USERNAME }}
          password: ${{ secrets.TESTAPPUP2_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: catestappup25826093093acr.azurecr.io/testappup-2:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TESTAPPUP2_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n testappup-2 -g sisirap-rg --server catestappup25826093093acr.azurecr.io --username  ${{ secrets.TESTAPPUP2_REGISTRY_USERNAME }} --password ${{ secrets.TESTAPPUP2_REGISTRY_PASSWORD }}
            az containerapp update -n testappup-2 -g sisirap-rg --image catestappup25826093093acr.azurecr.io/testappup-2:${{ github.sha }}
