name: Trigger auto deployment for containerapp testappup-new

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/testappup-new-AutoDeployTrigger-4b786cc4-71ce-4c72-98c8-f2d355654210.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: catestappupnacr.azurecr.io
          username: ${{ secrets.TESTAPPUPNEW_REGISTRY_USERNAME }}
          password: ${{ secrets.TESTAPPUPNEW_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: catestappupnacr.azurecr.io/testappup-new:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TESTAPPUPNEW_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n testappup-new -g sisirap-newrg --server catestappupnacr.azurecr.io --username  ${{ secrets.TESTAPPUPNEW_REGISTRY_USERNAME }} --password ${{ secrets.TESTAPPUPNEW_REGISTRY_PASSWORD }}
            az containerapp update -n testappup-new -g sisirap-newrg --image catestappupnacr.azurecr.io/testappup-new:${{ github.sha }}
